### ISSUE TITLE
Use /usr/bin/env python

### ISSUE THREAD

**Issue by nyxtom** [batiste/django-rpg#1]
GitHub sucks for this because I can't directly comment on your code... alas. I suggest in run.py using #!/usr/bin/env python so it respects virtual environments.

**Comment by batiste** [comment]
Hi,

You would like to comment my code? I know you can comment commits at least. I will add what you recommand.

Cheers

**Comment by batiste** [comment]
https://github.com/batiste/django-rpg/commit/6222bdca162da68f6a2906a2d73d6e79b6acfdc7

**Comment by nyxtom** [comment]
Cool! Also, have you leveraged redis.io pubsub with gevent at all?

**Comment by batiste** [comment]
Not at all, this game remain an quite simple experiment. I see how redis would probably be a better storage database for it.
